config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "followers" => "relationships#followers", as: "followers"
    resources :chats, only: [:index, :create]
    get "date" => "users#date"
  end
  resources :groups, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :participations, only: [:create, :destroy]
    resource :events, only: [:new, :create]
  end
  get "search" => "searches#search"


  root to: "homes#top"
  get "home/about"=>"homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :visitors

  has_many :tags_relationships, class_name: "BookTag", dependent: :destroy
  has_many :tags, through: :tags_relationships

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :evaluation, presence: true

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment_body, presence: true, length:{maximum:200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :participations

  has_many :group_members, class_name: "Participation", foreign_key: "group_id", dependent: :destroy
  has_many :members, through: :group_members, source: :user

  validates :name,presence:true
  validates :introduction, presence:true,length:{maximum:200}
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User" #ユーザーA：ユーザーBをフォローしている
  belongs_to :follower, class_name: "User" #ユーザーA：ユーザーBにフォローされている


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :books_relationships, class_name: "BookTag"
  has_many :books, through: :books_relationships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followed_users, through: :reverse_relationships, source: :following

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :following_users, through: :relationships  , source: :follower

  has_many :own_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy

  has_many :groups_participation, class_name: "Participation", foreign_key: "user_id", dependent: :destroy
  has_many :participating_groups, through: :groups_participation, source: :group

  has_many :chats_sent, class_name: "Chat", foreign_key: "sender_id", dependent: :destroy
  has_many :chats_received, class_name: "Chat", foreign_key: "receiver_id", dependent: :destroy

  has_many :visitors, foreign_key: "visitor_id"

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def following(following) #user_a.following(user_b) => user_a has been followed by user_b
    Relationship.find_by(following_id: following.id, follower_id: id)
  end

  def follower(follower) #user_a.follower(user_b) => user_a has been following user_b
    Relationship.find_by(following_id: id, follower_id: follower.id)
  end
=begin
  def following_users
    Relationship.where(following_id: id)
  end

  def followed_users
    Relationship.where(follower_id: id)
  end
=end

  def posts_n_days_ago(num)
    self.books.count{|x| (Time.zone.today.days_ago(num).at_beginning_of_day..Time.zone.today.days_ago(num).at_end_of_day).cover?(x.created_at)}
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :visitor, class_name: "User"
  belongs_to :book
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    current_user.own_groups.new(group_params).save
    redirect_to groups_path
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.members
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to group_path(params[:id])
  end

  def destroy
    Group.find(params[:id]).destroy
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="container w-50">
  <div class="d-flex justify-content-between mb-3">
    <h2 class="d-flex mb-0">Edit group</h2>
    <%= link_to "Remove", group_path,method: :delete, class: "d-flex btn btn-danger align-items-center px-3 ml-3", "data-confirm" => "グループを削除しますか？" %>
  </div>
    <%= form_with model: @group, local:true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control book_title' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction , "Opinion" %>
      <%= f.text_area :introduction, class: 'form-control book_body' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class="table w-75 table-striped">
        <thead>
          <th class="col-5 align-middle text-center">name</th>
          <th class="col-5 align-middle text-center">owner</th>
          <th class="col-2 align-middle text-center">number of members</th>
        </thead>
        <tbody>
          <% @groups.each do |item| %>
            <tr>
              <td class="align-middle text-center"><%= link_to item.name, group_path(item.id), class: "d-block" %></td>
              <td class="align-middle text-center"><%= link_to User.find(item.owner_id).name, user_path(item.owner_id), class: "d-block" %></td>
              <td class="align-middle text-right"><%= item.members.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container w-50">
  <h2>New group</h2>
  <%= form_with model: @group, local:true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control book_title' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction , "Opinion" %>
      <%= f.text_area :introduction, class: 'form-control book_body' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <% if !@sent %>
      <div class='col-md-8 offset-md-1'>
      <div>
        <h6 class="mb-0">Group</h6>
        <div class="d-flex justify-content-between">
          <h2 class="mb-0"><%= @group.name %></h2>
          <div class="d-flex align-items-center">
            <%= link_to "Owner&nbsp;: #{User.find(@group.owner_id).name}".html_safe, user_path(@group.owner_id) %>
            <% if @group.owner_id == current_user.id %>
              <%= " (you)" %>
              <%= link_to "Edit", edit_group_path, class: "d-flex btn btn-outline-info align-items-center px-3 ml-3" %>
            <% elsif @group.members.find_by(id: current_user.id).nil? %>
              <%= link_to "Join this group", group_participations_path(@group.id), method: :post, class: "d-flex btn btn-primary align-items-center px-3 ml-3" %>
            <% else %>
              <%= link_to "Leave this group", group_participations_path(@group.id), method: :delete, class: "d-flex btn btn-warning align-items-center px-3 ml-3" %>
            <% end %>
          </div>
        </div>
      </div>
      <% if @group.owner_id == current_user.id %>
        <div class="ml-5 d-flex justify-content-between">
          <p><%= @group.introduction %></p>
          <%= link_to "Notice an event", new_group_events_path(@group.id), class: "btn btn-info" %>
        </div>
      <% end %>
      <div class="d-flex mt-4">
        <div class="group_members_list col-7">
          <div class="d-flex">
            <h2>Group members</h2>
            <h6 class="mt-auto ml-auto"><%= pluralize(@members.count, "member") %></h6>
          </div>
          <table class="table table-striped">
            <thead></thead>
            <tbody>
              <% @members.each do |member| %>
                <tr>
                  <td>
                    <%= link_to user_path(member.id) do %>
                      <div><%= member.name %></div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!--div class="events_list col-6">
          <div class="d-flex">
            <h2>Events</h2>
            <h6 class="mt-auto ml-auto"><%#= pluralize(0, "event") %></h6>
          </div>
          <table class="table table-striped">
            <thead></thead>
            <tbody>
              <%# @members.each do |member| %>
                <tr>
                  <td>
                    <%#= link_to user_path(member.id) do %>
                      <div><%#= member.name %></div>
                    <%# end %>
                  </td>
                </tr>
              <%# end %>
            </tbody>
          </table>
        </div-->
      </div>
    </div>
    <% else %>
      <div class="mx-auto mt-5 mb-auto p-3 border border-success rounded bg-light shadow">
        <h4>E-mail has been finished sending.</h4>
        <table>
          <tr>
            <th class="pr-5">Group</th>
            <td><%= Group.find(@event[:group_id]).name %></td>
          </tr>
          <tr>
            <th class="pr-5">Title</th>
            <td><%= @event[:title] %></td>
          </tr>
          <tr>
            <th class="pr-5">Detail</th>
            <td><%= @event[:detail] %></td>
          </tr>
        </table>
      </div>
    <% end %>
    </div>
</div>