config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "followers" => "relationships#followers", as: "followers"
    resources :chats, only: [:index, :create]
    get "date" => "users#date"
  end
  resources :groups, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :participations, only: [:create, :destroy]
    resource :events, only: [:new, :create]
  end
  get "search" => "searches#search"


  root to: "homes#top"
  get "home/about"=>"homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :visitors

  has_many :tags_relationships, class_name: "BookTag", dependent: :destroy
  has_many :tags, through: :tags_relationships

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :evaluation, presence: true

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment_body, presence: true, length:{maximum:200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :participations

  has_many :group_members, class_name: "Participation", foreign_key: "group_id", dependent: :destroy
  has_many :members, through: :group_members, source: :user

  validates :name,presence:true
  validates :introduction, presence:true,length:{maximum:200}
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User" #ユーザーA：ユーザーBをフォローしている
  belongs_to :follower, class_name: "User" #ユーザーA：ユーザーBにフォローされている


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :books_relationships, class_name: "BookTag"
  has_many :books, through: :books_relationships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followed_users, through: :reverse_relationships, source: :following

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :following_users, through: :relationships  , source: :follower

  has_many :own_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy

  has_many :groups_participation, class_name: "Participation", foreign_key: "user_id", dependent: :destroy
  has_many :participating_groups, through: :groups_participation, source: :group

  has_many :chats_sent, class_name: "Chat", foreign_key: "sender_id", dependent: :destroy
  has_many :chats_received, class_name: "Chat", foreign_key: "receiver_id", dependent: :destroy

  has_many :visitors, foreign_key: "visitor_id"

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def following(following) #user_a.following(user_b) => user_a has been followed by user_b
    Relationship.find_by(following_id: following.id, follower_id: id)
  end

  def follower(follower) #user_a.follower(user_b) => user_a has been following user_b
    Relationship.find_by(following_id: id, follower_id: follower.id)
  end
=begin
  def following_users
    Relationship.where(following_id: id)
  end

  def followed_users
    Relationship.where(follower_id: id)
  end
=end

  def posts_n_days_ago(num)
    self.books.count{|x| (Time.zone.today.days_ago(num).at_beginning_of_day..Time.zone.today.days_ago(num).at_end_of_day).cover?(x.created_at)}
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :visitor, class_name: "User"
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    now = Time.zone.now
    @posts_today = @books.count{|x| (now.at_beginning_of_day..now.at_end_of_day).cover?(x.created_at)}
    @posts_yesterday = @books.count{|x| (now.yesterday.at_beginning_of_day..now.yesterday.at_end_of_day).cover?(x.created_at)}
    @posts_this_week = @books.count{|x| (now.days_ago(6).at_beginning_of_day..now.at_end_of_day).cover?(x.created_at)}
    @posts_last_week = @books.count{|x| (now.days_ago(13).at_beginning_of_day..now.days_ago(7).at_end_of_day).cover?(x.created_at)}
    
  end

  def date
    user = User.find(params[:user_id])
    period = params[:date].to_date.all_day
    @num_books = user.books.count{|x| period.cover?(x.created_at)}
    render "dateviewer"
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td>
          <%= user.following_users.count %> following
        </td>
        <td>
          <%= pluralize(user.followed_users.count, "follower") %>
        </td>
        <td>
          <% if user != current_user %>
            <% if user.following(current_user).nil? %>
              <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-primary font-weight-bold rounded-pill px-4"  %>
            <% else %>
              <%= link_to "Following", user_relationships_path(user.id), method: :delete, class: "btn btn-light border-dark font-weight-bold rounded-pill px-3 follow" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th><%= link_to "following", user_following_path(user.id) %></th>
    <th><%= link_to user.following_users.count, user_following_path(user.id) %></th>
  </tr>

  <tr>
    <th><%= link_to "follower".pluralize(user.followed_users.count), user_followers_path(user.id) %></th>
    <th><%= link_to user.followed_users.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class="row justify-content-center mb-3">
  <% if user != current_user %>
    <% if user.following(current_user).nil? %>
      <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-primary font-weight-bold px-4 rounded-pill" %>
    <% else %>
      <%= link_to "Following", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-dark font-weight-bold px-3 rounded-pill" %>
    <% end %>
  <% end %>
</div>
<% if (!user.following(current_user).nil? && !user.follower(current_user).nil?) || (user.chats_sent.count{|x| x.receiver_id == current_user.id} + user.chats_received.count{|x| x.sender_id == current_user.id} > 0) %>
  <div class="row justify-content-center mb-3">
    <%= link_to "chat", user_chats_path(user.id), class: "btn btn-success px-3 rounded-pill" %>
  </div>
<% end %>
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>Update User Info
  <% end %>
</div>

app/views/users/dateviewer.js.erb
$(".get_date_search").html(`
  <table class="table border-bottom w-50">
    <thead>
      <tr>
        <th><%= params[:date].to_date.strftime("%Y年%-m月%-d日の投稿数") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @num_books %></td>
      </tr>
    </tbody>
  </table>
`);

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div>
        <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      </div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <div>
        <p>投稿数の前日比・前週比</p>
        <table class="table border-bottom">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @posts_today %></td>
              <td><%= @posts_yesterday %></td>
              <td>
                <% if @posts_yesterday == 0 %>
                  ---
                <% else %>
                  <%= "#{(@posts_today.to_f / @posts_yesterday.to_f * 100).round(1)} %" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <table class="table border-bottom ">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @posts_this_week %></td>
              <td><%= @posts_last_week %></td>
              <td>
                <% if @posts_last_week == 0 %>
                  ---
                <% else %>
                  <%= "#{(@posts_this_week.to_f / @posts_last_week.to_f * 100).round(1)}" %>  
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <p>7日間分の投稿数</p>
        <table  class="table 7days_post border-bottom">
          <thead>
            <tr>
              <th>6日前</th>
              <th>5日前</th>
              <th>4日前</th>
              <th>3日前</th>
              <th>2日前</th>
              <th>昨日</th>
              <th>本日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @user.posts_n_days_ago(6) %></td>
              <td><%= @user.posts_n_days_ago(5) %></td>
              <td><%= @user.posts_n_days_ago(4) %></td>
              <td><%= @user.posts_n_days_ago(3) %></td>
              <td><%= @user.posts_n_days_ago(2) %></td>
              <td><%= @user.posts_n_days_ago(1) %></td>
              <td><%= @user.posts_n_days_ago(0) %></td>
            </tr>
          </tbody>
        </table>
        <canvas id="myChart"></canvas>
      </div>
      <div>
        <p>指定日の投稿数</p>
        <%= form_with local: false, method: :get, url: user_date_path(@user) do |f| %>
          <%= f.date_field :date, value: Time.zone.today %>
          <%= f.submit "View" %>
        <% end %>
        <div class="get_date_search mt-2"></div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('turbolinks:load', function () {
    var ctx = document.getElementById('myChart');
    function day(num){
      return $(".7days_post thead th")[6 - num].innerText
    }
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: [
          day(6),
          day(5),
          day(4),
          day(3),
          day(2),
          day(1),
          day(0)],
        datasets: [{
          label: '# of posts',
          data: [
            <%= @user.posts_n_days_ago(6) %>,
            <%= @user.posts_n_days_ago(5) %>,
            <%= @user.posts_n_days_ago(4) %>,
            <%= @user.posts_n_days_ago(3) %>,
            <%= @user.posts_n_days_ago(2) %>,
            <%= @user.posts_n_days_ago(1) %>,
            <%= @user.posts_n_days_ago(0) %>          
          ],
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 101, 178, 0.2)'
          ],
          borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)',
            'rgba(255, 101, 178, 1)'
          ],
          borderWidth: 2,
          pointStyle: 'circle',
          pointRadius: 10,
          pointHoverRadius: 20
        }]
      },
      options: {

        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  });
</script>