config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "followers" => "relationships#followers", as: "followers"
    resources :chats, only: [:index, :create]
    get "date" => "users#date"
  end
  resources :groups, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :participations, only: [:create, :destroy]
    resource :events, only: [:new, :create]
  end
  get "search" => "searches#search"


  root to: "homes#top"
  get "home/about"=>"homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :visitors

  has_many :tags_relationships, class_name: "BookTag", dependent: :destroy
  has_many :tags, through: :tags_relationships

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :evaluation, presence: true

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment_body, presence: true, length:{maximum:200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :participations

  has_many :group_members, class_name: "Participation", foreign_key: "group_id", dependent: :destroy
  has_many :members, through: :group_members, source: :user

  validates :name,presence:true
  validates :introduction, presence:true,length:{maximum:200}
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User" #ユーザーA：ユーザーBをフォローしている
  belongs_to :follower, class_name: "User" #ユーザーA：ユーザーBにフォローされている


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :books_relationships, class_name: "BookTag"
  has_many :books, through: :books_relationships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followed_users, through: :reverse_relationships, source: :following

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :following_users, through: :relationships  , source: :follower

  has_many :own_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy

  has_many :groups_participation, class_name: "Participation", foreign_key: "user_id", dependent: :destroy
  has_many :participating_groups, through: :groups_participation, source: :group

  has_many :chats_sent, class_name: "Chat", foreign_key: "sender_id", dependent: :destroy
  has_many :chats_received, class_name: "Chat", foreign_key: "receiver_id", dependent: :destroy

  has_many :visitors, foreign_key: "visitor_id"

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def following(following) #user_a.following(user_b) => user_a has been followed by user_b
    Relationship.find_by(following_id: following.id, follower_id: id)
  end

  def follower(follower) #user_a.follower(user_b) => user_a has been following user_b
    Relationship.find_by(following_id: id, follower_id: follower.id)
  end
=begin
  def following_users
    Relationship.where(following_id: id)
  end

  def followed_users
    Relationship.where(follower_id: id)
  end
=end

  def posts_n_days_ago(num)
    self.books.count{|x| (Time.zone.today.days_ago(num).at_beginning_of_day..Time.zone.today.days_ago(num).at_end_of_day).cover?(x.created_at)}
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :visitor, class_name: "User"
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @users = User.all
    @book = Book.find(params[:id])
    @comment = Comment.new
    Visitor.create(book_id: @book.id, visitor_id: current_user.id) unless Visitor.find_by(book_id: @book.id, visitor_id: current_user.id)
  end

  def index
    if params[:sort] == "fav"
      now = Time.zone.now
      #指定期間のいいねを取得
      favorites = Favorite.where(created_at: (now.days_ago(6).at_beginning_of_day)..(now.at_end_of_day))
      #日時降順でソートし、book_idを配列で取得
      arr = favorites.order(created_at: :DESC).pluck(:book_id)
      #いいねの個数順（配列内で同じ値の個数）降順
      books_searched = Book.find(arr.sort{|a,b| arr.count(b) - arr.count(a)})
      books_remainder = Book.all - books_searched

      @books = books_searched + books_remainder
    elsif params[:sort] == "eval"
      @books = Book.order(evaluation: :DESC)
    else
      @books = Book.order(created_at: :DESC)
    end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @tags_value = tags_value

    if @book.save
      save_tags
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @tags_value = @book.tags.pluck(:name).join(" ")
    redirect_to books_path if @book.user != current_user
  end

  def update
    @book = Book.find(params[:id])
    @tags_value = tags_value
    if @book.update(book_params)
      save_tags
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def save_tags
    tags = params[:book][:tag_name].split(" ")
    tags.each do |t|
      if Tag.find_by(name: t).nil? then Tag.new(name: t).save end
      tag = Tag.find_by(name: t)
      @book.tags_relationships.new(tag_id: tag.id).save if @book.tags_relationships.find_by(tag_id: tag.id).nil?
    end
    @book.tags.each do |t|
      @book.tags_relationships.find_by(tag_id: t.id).destroy unless tags.include?(t.name)
    end
  end

  def tags_value
    params[:book][:tag_name].nil? ? self.tags.pluck(:name).join(" ") : params[:book][:tag_name]
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :evaluation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_evaluation.html.erb
<div id="rate_<%= book.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#rate_<%= book.id %>').empty();
  $('#rate_<%= book.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    //starHalf: '<%#= asset_path('star-half.png') %>',
    //half: true,
    readOnly: true,
    score: <%= book.evaluation %>,
  });
});
</script>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "mb-0" %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body , "Opinion", class: "mb-0" %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label "Tag(s) (space separating)", class: "mb-0" %>
    <%= f.text_field :tag_name, value: @tags_value, class: 'form-control book_title' %>
  </div>
  <div class="evaluation mb-3">
    <%= f.label :evaluation, class: "mb-0" %>
    <%= f.hidden_field :evaluation %>
    <div id="evaluation"></div>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
  <% if book.evaluation.nil? %>
    <script>
      $('#evaluation').empty();
      $('#evaluation').raty({
        size: 8,
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        //starHalf: "<%#= asset_path('star-half.png') %>",
        scoreName: 'book[evaluation]' //登録するモデル名とカラム名を記述
      });
    </script>
  <% else %>
    <%= render "evaluation", book: book %>
  <% end %>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse table-striped'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td class="align-middle col-1">
          <%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td class="align-middle col-2"><%= link_to book.title,book %></td>
        <td class="align-middle col-3"><%= book.body %></td>
        <td class="align-middle col-3">
            <div id=<%= "fav-book-#{book.id}" %>>
              <%= render 'favorites/fav', book: book %>
            </div>
            <p class="m-0"><%= book.comments.count %> コメント</p>
            <p class="m-0">閲覧者数：<%= book.visitors.count %></p>
        </td>
        <td class="align-middle col-3">
          <%= render "books/evaluation", book: book %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div>
        <%= link_to "新しい順", books_path(sort: "new") %>
        |
        <%= link_to "1週間のいいね数順", books_path(sort: "fav") %>
        |
        <%= link_to "評価順", books_path(sort: "eval") %>
      </div>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <section class="book_detail">
    		<h2>Book detail</h2>
    		<table class='table'>
    		  <tr>
            <td rowspan="2" class="col-2"><%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td rowspan="2" class="col-2"><%= link_to @book.title, @book %></td>
            <td rowspan="2" class="col-3"><%= @book.body %></td>
            <td class="col-3">
              <div id=<%= "fav-book-#{@book.id}" %>>
                <%= render 'favorites/fav', book: @book %>
              </div>
              <div>
                <p>閲覧者数：<%= @book.visitors.count %></p>
              </div>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <%= render "books/evaluation", book: @book %>
            </td>
          </tr>
          <tr>
            <td class="h6 font-weight-bold">
              <%= pluralize(@book.tags.count, "Tag") %>
            </td>
            <td colspan="5">
              <% @book.tags.each do |tag| %>
                <%= link_to tag.name, search_path(tag: tag.name, search: "タグ検索") %>
              <% end %>
            </td>
          </tr>
        </table>
      </section>
      <section class="comments">
        <div class="new_comment">
          <h2>Post new comment</h2>
          <%= render 'layouts/errors', obj: @comment %>
          <%= form_with model: [@book, @comment], local: false do |f| %>
          <div class="form-group">
            <%= f.label :comment_body, "Comment" %>
            <%= f.text_area :comment_body, class: "comment-input-area form-control w-50" %>
          </div>
          <div class="form-group">
            <%= f.submit "Post Comment", class: "btn btn-success" %>
          </div>
          <% end %>
        </div>
        <div class="comments_list">
          <%= render 'comments/comments' %>
        </div>
      </section>
    </div>
  </div>
</div>