config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "following" => "relationships#following", as: "following"
    get "followers" => "relationships#followers", as: "followers"
    resources :chats, only: [:index, :create]
    get "date" => "users#date"
  end
  resources :groups, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :participations, only: [:create, :destroy]
    resource :events, only: [:new, :create]
  end
  get "search" => "searches#search"


  root to: "homes#top"
  get "home/about"=>"homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :visitors

  has_many :tags_relationships, class_name: "BookTag", dependent: :destroy
  has_many :tags, through: :tags_relationships

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :evaluation, presence: true

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  validates :body, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment_body, presence: true, length:{maximum:200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :participations

  has_many :group_members, class_name: "Participation", foreign_key: "group_id", dependent: :destroy
  has_many :members, through: :group_members, source: :user

  validates :name,presence:true
  validates :introduction, presence:true,length:{maximum:200}
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User" #ユーザーA：ユーザーBをフォローしている
  belongs_to :follower, class_name: "User" #ユーザーA：ユーザーBにフォローされている


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :books_relationships, class_name: "BookTag"
  has_many :books, through: :books_relationships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followed_users, through: :reverse_relationships, source: :following

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :following_users, through: :relationships  , source: :follower

  has_many :own_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy

  has_many :groups_participation, class_name: "Participation", foreign_key: "user_id", dependent: :destroy
  has_many :participating_groups, through: :groups_participation, source: :group

  has_many :chats_sent, class_name: "Chat", foreign_key: "sender_id", dependent: :destroy
  has_many :chats_received, class_name: "Chat", foreign_key: "receiver_id", dependent: :destroy

  has_many :visitors, foreign_key: "visitor_id"

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def following(following) #user_a.following(user_b) => user_a has been followed by user_b
    Relationship.find_by(following_id: following.id, follower_id: id)
  end

  def follower(follower) #user_a.follower(user_b) => user_a has been following user_b
    Relationship.find_by(following_id: id, follower_id: follower.id)
  end
=begin
  def following_users
    Relationship.where(following_id: id)
  end

  def followed_users
    Relationship.where(follower_id: id)
  end
=end

  def posts_n_days_ago(num)
    self.books.count{|x| (Time.zone.today.days_ago(num).at_beginning_of_day..Time.zone.today.days_ago(num).at_end_of_day).cover?(x.created_at)}
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :visitor, class_name: "User"
  belongs_to :book
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if !obj.nil? && obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <% if user_signed_in? %>
        <div class="search_form mr-1">
          <%= form_with url: search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
            <%= f.text_field :query, class: "form-control w-50", value: params[:query] %>
            <%= f.select :model, options_for_select([['User'], ['Book']]), class: "form-select" %>
            <%= f.select :search_method, options_for_select([["完全一致","perfect"], ["前方一致","forward"],  ["後方一致","backward"], ["部分一致","partial"]]), class: "form-select" %>
            <%= f.submit "検索", name: "search", class: "btn btn-primary " %>
          <% end %>
        </div>
        <div class="tag_search_form">
          <%= form_with url: search_path, local: true, method: :get, class: "d-flex align-items-center" do |f| %>
            <%= f.text_field :tag, class: "form-control w-50", value: params[:tag] %>
            <%= f.submit "タグ検索", name: "search", class: "btn btn-primary " %>
          <% end %>
        </div>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> about
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>